/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function TestWeaponGun(props) {
  const { nodes, materials } = useGLTF('/TestWeaponGun.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Weapon_Gun.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/TestWeaponGun.gltf')
